language: python
python:
  "3.5"
services:
  - mongodb
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  nosetests --with-coverage --cover-package=src
after_success:
  coveralls
