api:
  build: .
  command: python3 src/stockreader.py config-docker.toml
  ports:
    - "5000:5000"
  links:
    - mongodb
    - influxdb

mongodb:
  image: mongo:3
  ports:
    - "27017:27017"
  volumes:
    - /data/db/:/data/db

influxdb:
  image: influxdb:1.0.2
  ports:
    - "8083:8083"
    - "8086:8086"
  volumes:
    - /var/lib/influxdb:/var/lib/influxdb

grafana:
  image: grafana/grafana:3.1.1-1470047149
  ports:
    - 3000:3000
  volumes:
    - /var/lib/grafana:/var/lib/grafana
  environment:
    GF_USERS_ALLOW_SIGN_UP: "false"
