[server]
host = "localhost"
port = 5000
debug = true

[mariadb]
host = "localhost"
port = 3306
username = "root"
password = "qwe"
database = "stockreaderdb"
pool_name = "mariadb_pool"
pool_size = 10

[influx]
host = "localhost"
port = 8086
username = ""
password = ""
database = "stockreaderdb"

[exchanges]
nyse = [
  "resources/NYSE-Volume-Percentage-Movers-2016-03-21.csv",
  "resources/NYSE-Most-Active-Stocks-2016-03-21.csv",
  "resources/NYSE-Biggest-Percentage-Gainers-2016-03-21.csv",
  "resources/NYSE-Biggest-Percentage-Decliners-2016-03-21.csv"
]

nasdaq = [
  "resources/Nasdaq-Volume-Percentage-Movers-2016-03-21.csv",
  "resources/Nasdaq-Most-Active-Stocks-2016-03-21.csv",
  "resources/Nasdaq-Biggest-Percentage-Gainers-2016-03-21.csv",
  "resources/Nasdaq-Biggest-Percentage-Decliners-2016-03-21.csv"
]
